# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0064d89fa9a49733f1ade351b92c373d674a77bc1edf3d30da578d2efc36cb0fdfa4f460a1fc69a7f3dd5e76b063f10b3405496e2da4b32286ace9a3a51ca78f

test:
  secret_key_base: c17fc52691b6cc9cd509e686200b39cb004346f7db381664868a4c1e77c8e9a9d6de820f18eb548d5e15a42f3ee4129a8670236f63096a7e31ced2223f356923

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
